# Generated by Django 3.1.2 on 2021-01-04 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20210103_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viewcount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 22, 17, 0, 89149), null=True),
        ),
    ]
