# Generated by Django 3.1.2 on 2021-01-04 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20210104_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 22, 20, 52, 931283), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='viewcount',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
