# Generated by Django 3.1.2 on 2020-11-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_auto_20201109_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcat',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
