# Generated by Django 3.1.2 on 2020-11-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_auto_20201111_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descrption',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
