# Generated by Django 3.1.2 on 2020-11-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_auto_20201117_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='cpassword',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
