# Generated by Django 3.1.2 on 2020-11-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_orderitems_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='urgent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
