# Generated by Django 3.1.2 on 2020-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_orderitems_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='phone',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
