# Generated by Django 3.1.2 on 2020-11-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0020_orderitems_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='urgent',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='urgentstatus',
            field=models.BooleanField(default=False),
        ),
    ]
