# Generated by Django 3.1.2 on 2020-11-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0021_auto_20201126_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='urgentstatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
