# Generated by Django 3.1.2 on 2020-11-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0022_auto_20201126_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='crossprice',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='homefeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offpercent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='homeapp.Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='homeapp.Size'),
        ),
    ]
