# Generated by Django 3.1.2 on 2020-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0023_auto_20201128_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(null=True, to='homeapp.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(null=True, to='homeapp.Size'),
        ),
    ]
