# Generated by Django 3.1.2 on 2020-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0025_auto_20201129_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
