# Generated by Django 3.1.2 on 2020-12-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0026_patron_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='cpassword',
        ),
    ]
