# Generated by Django 3.1.2 on 2020-12-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0027_remove_patron_cpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='cpassword',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
