# Generated by Django 3.1.2 on 2020-12-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0028_patron_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_image', models.ImageField(blank=True, null=True, upload_to='pictures/ads')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
