# Generated by Django 3.1.2 on 2020-12-15 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0029_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='created_at',
            field=models.DateField(default=datetime.datetime.today, null=True),
        ),
    ]
