# Generated by Django 3.1.2 on 2020-12-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0031_auto_20201215_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='recent_arrival',
            field=models.BooleanField(default=False),
        ),
    ]
