# Generated by Django 3.1.2 on 2020-12-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0032_auto_20201217_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertise',
            old_name='created1_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='advertise',
            old_name='website1',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='created2_at',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='created3_at',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='created4_at',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='created5_at',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='website2',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='website3',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='website4',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='website5',
        ),
        migrations.AddField(
            model_name='advertise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%d'),
        ),
    ]
