# Generated by Django 3.1.2 on 2020-12-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0033_auto_20201217_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertise',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='orderitems',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'Khalti')], default='Cash On Delivery', max_length=20),
        ),
    ]
