# Generated by Django 3.1.2 on 2020-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0034_auto_20201219_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
