# Generated by Django 3.1.2 on 2020-12-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0035_orderitems_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
