# Generated by Django 3.1.2 on 2020-12-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0036_cart_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='payment_method',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
