# Generated by Django 3.1.2 on 2020-12-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0038_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
