# Generated by Django 3.1.2 on 2020-12-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0040_auto_20201224_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='created',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
