# Generated by Django 3.1.2 on 2020-12-24 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0041_auto_20201224_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 10, 9, 40, 340441), null=True),
        ),
    ]
