# Generated by Django 3.1.2 on 2020-12-24 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0042_auto_20201224_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 14, 40, 9, 652229), null=True),
        ),
    ]
