# Generated by Django 3.1.2 on 2020-12-26 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0045_auto_20201224_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 18, 46, 41, 537735), null=True),
        ),
    ]
