# Generated by Django 3.1.2 on 2020-12-26 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0046_auto_20201226_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 18, 46, 55, 231079), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
