# Generated by Django 3.1.2 on 2020-12-27 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0048_auto_20201227_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 10, 19, 10, 552436), null=True),
        ),
    ]
