# Generated by Django 3.1.2 on 2020-12-27 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0050_auto_20201227_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 10, 21, 55, 103545), null=True),
        ),
    ]
