# Generated by Django 3.1.2 on 2020-12-27 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0051_auto_20201227_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 10, 23, 56, 889789), null=True),
        ),
    ]
